const AWS_ACCESS_KEY= process.env.AWS_ACCESS_KEY;
const AWS_BUCKET = 'maynhac-de034739-e333-4019-a8fe-98be19dc6ca6';
const AWS_SECRET_ACCESS_KEY=process.env.AWS_SECRET_ACCESS_KEY;

module.exports = {AWS_ACCESS_KEY, AWS_BUCKET, AWS_SECRET_ACCESS_KEY}
